name: portfolio_sabin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  responsive_framework: ^1.4.0
  url_launcher: ^6.2.5
  lottie: ^3.1.0
  carousel_slider: ^4.2.1
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/
    - assets/images/projects/
    - assets/images/projects/agl/
    - assets/images/projects/figma2flutter/
    - assets/images/projects/scully/
    - assets/images/projects/divine_bullion/
    - assets/images/projects/moneypool/






